### ISSUE TITLE
What's wrong with the symbols tab?

### ISSUE THREAD

**Issue by mrexodia** [0ffffffffh/Api-Break-for-x64dbg#1]
Just curious since it looks like this exact behavior is available in the symbols tab, even with searching...

**Comment by 0ffffffffh** [comment]
Hi @mrexodia, Thank you for your interest.

The main goal to develop this plugin is that make easier to do. And will be provided some extra features when it arrives the final version. (Grouping as API category and set breakpoint to specified group, Dynamic API detection for GetProcAddress usage etc.) Yes, you can achieve same result using with the symbol info indirectly or intermodular calls. But obviously, you have to take a lot of steps to do it. And you have to waste bunch of a time to achieve same result.  To do this with symbol tab, you must search the API symbol on the Symbol tab first, then jump to the API function address and setting a breakpoint. When you hit the breakpoint of the API's entry you must jump to previous calller using callstack. Or with in the Intermoduler calls window; you have to manually search all module calls and set breakpoints to all of the API calls. 

In this plugin, just select the module and desired API of the module from the combolist and set option from the checkbox. No need to switch any tab or window, typing or something. As I said before, the main goal is easier, usable and time saver extension to do this job. For a little example; To prevent the breakpoint hell the plugin provides an option that backtrace to original caller automatically when API entry breakpoint hit.  

This plugin is a choice that how you want to do.

I hope I convicted you with my answer.

**Comment by samoray22** [comment]
Personally I like the idea, it can be a great help for noob like me :)

**Comment by mrexodia** [comment]
@0ffffffffh There is no need to convince me of the use of your plugin, I just wanted to make sure that you didn't miss any of the built-in features to make sure no time is wasted :)

There is a plugin for category breakpoints from a menu called [SlothBP](https://github.com/x64dbg/SlothBP) and note that you can press F2 directly in the symbol view to set a breakpoint on the API you like.

The features for breaking on the caller and such are obviously not in x64dbg, I didn't catch those from the description.
