### ISSUE TITLE
no debug process

### ISSUE THREAD

**Issue by stonedreamforest** [0ffffffffh/Api-Break-for-x64dbg#5]
![default](https://cloud.githubusercontent.com/assets/16742566/22631828/89b0ae58-ec4e-11e6-9b97-82c952bed642.png)

**Comment by 0ffffffffh** [comment]
Ok. I'm on it. But I need to ask about the issue.

Is it happens for a specific process? Or is it happens for every process?
If its occurs for a specific process, Can you share with me what process is it?

Extra info : Let me explain the background of this issue. The plugin uses debugger's API to detect "is there any being debugged process?" And it seems the debugger returns zero to the plugin and plugin says oh there is no debugged process. 

I've replaced the detection routine's implementation with more stable variant I thought. Its already committed. And I will be release more stable version. 

Thanks.

**Comment by stonedreamforest** [comment]
happens for every process

**Comment by stonedreamforest** [comment]
attach process ->plugin ->set an api breakkpoint

**Comment by 0ffffffffh** [comment]
Ah now I reproduced the issue now. It happens trying to attach process. I'll fix it. Thanks.
