### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Saya47** [0ffffffffh/Api-Break-for-x64dbg#9]
Hello, I have x64dbg copied to a folder,
Now where should I put the .dp32 and .dp64 files? What path in the x64dbg folder?
Thanks very much! :)

**Comment by 0ffffffffh** [comment]
Hi you have to put the plugin binary into plugins directory of x64dbg. X64DBGROOTDIR/[ARCHITECTURE]/plugins. You have to move dp32 into "x32/plugins" and dp64 into "x64/plugins"

**Comment by Saya47** [comment]
Thanks very much!
